### ISSUE TITLE
Detect and ignore duplicate submissions

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#1006]
User may accidentally make a submission that is exact duplicate of an earlier submission for the same exercise. A+ could detect and ignore these submissions, to avoid unnecessary consuming available submissions for the exercise.

**Comment by Mankro** [comment]
Duplicate of #513. There are some concerns there:

> Student should be warned when they are about to consume an attemt for already submitted solution.
>
> A+ could resubmit the older submission for regrading, which would enable them to fix failed gradings them selfs, which does raise concerns for unlimited code executions in the backend.
>
> This could be implemented by calculating a hash value of the submission (all fields and files, sorted), exposing this hash back to the browser, which could compare the current submission to past hashes.

**Comment by Mankro** [comment]
Ideas:
* compute a hash of the submission so that the hashes can be compared. Identical hashes suggest that the submissions are identical.
* the hash should be computed over submitted files and `Submission.submission_data`
* the hash can be stored in the database in the field `Submission.meta_field`. It is a JSON field that contains other meta data as well. 
* the hash for each submission can be added to the cache (CachedPoints) so that reading the hashes of all submissions from one student is fast (no database queries if the data is already in the cache).
  * https://github.com/apluslms/a-plus/blob/4ed0d82b7ccc157123674caff4ed6469852c7818/exercise/cache/points.py#L304-L321

**Comment by Mankro** [comment]
Additional ideas for the implementation.

1. `CachedPoints`: creating a CachedPoints objects reads data from the cache or generates the data if it is missing from the cache. The constructor is here: https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/exercise/cache/points.py#L60-L66
  * As an example, the constructor is called in many places in the existing code including these: 
  * https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/exercise/api/csv/views.py#L98
  * https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/exercise/viewbase.py#L133
  * https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/course/permissions.py#L261
  * the CachedContent needed as a parameter usually already exists in the view classes as `self.content`: https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/course/viewbase.py#L60
  * **The next step is to find the correct data inside the cache object.**
  * The cache object has a method `find()`: https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/exercise/cache/hierarchy.py#L164
  * The parameter to find() could a BaseExercise instance: https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/exercise/cache/hierarchy.py#L252
  * `find()` returns a tuple. The first element is the dictionary for the exercise and it contains the key "submissions"
2. **when and where to check duplicates**: it is best to avoid creating the real submission object in the database if the submission should be declined due to the duplicate check. The duplicate check can be done with the data in the http request even before creating a new submission. The duplicate check could be implemented in a new method in the class SubmissionManager: https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/exercise/submission_models.py#L128
  * `ExerciseView` could call the duplicate check method before creating the new submission. The existing `submission_check` method is appropriate for this: https://github.com/apluslms/a-plus/blob/d33fa893d426f165b62a1acbe4de4adfe4c7b647/exercise/views.py#L222
  * `submission_check` returns a list of warnings (amongst other values) and an error message about the duplicate submission should be included there.
3. **how to show warnings to the user**: if you use the submission_check method from the bullet 2 above, then submission_check returns a list of warnings that are displayed at the top of the exercise. That would follow the same approach that has been used with existing warnings in making submissions.

**Comment by ttsirkia** [comment]
How to handle the situations that the grader has had some bugs which are fixed when student would like to submit the same solution again?

**Comment by Mankro** [comment]
> How to handle the situations that the grader has had some bugs which are fixed and after that student would like to submit the same solution again?

The student is shown a confirmation dialog about whether he/she wants to submit a new identical submission.

**Comment by ttsirkia** [comment]
That makes sense. So the title of the issue is not accurate. Duplicates are not ignored, they are confirmed.

**Comment by Mankro** [comment]
@muhammadfaiz12 I think implementing the confirmation dialog in the frontend is much simpler if the duplicate check is actually done in the frontend. Then, duplicate submissions would never be uploaded to the server. If the hashes of the existing submissions are rendered in the HTML (data attributes), then frontend JavaScript can compute the hash for the new submission and compare the hash to the existing hashes. If it is a duplicate and the student wants to cancel the submission in the dialog, then no submission is ever sent to the server. This just requires that the hashes can be computed in frontend JavaScript in addition to the backend.

**Comment by muhammadfaiz12** [comment]
Yes that could also works but i think i need more explanation on how this would work. We could discuss this in the meeting.

**Comment by muhammadfaiz12** [comment]
**Handover Note**

**What is this and how it works?**
This feature check if a user will make a duplicate submission. If the system detects that the user will make a duplicate submission it will prompt a confirmation from the user. User would be able to submit the submission if they indicate so in the confirmation. No changes of behaviour happened if the user make a non-duplicate submission.

The system create a submission hash for submitted submission. this hash was stored in both Database and Cache. This hashes are rendered to Front end when user open exercise page. When user want to submit a submission, the front end system create hash of the submission and compare it to the old submissions hashes. Front end side create hash to compare new submission hash with the previous submissions hashes, Back end side then recompute the hash to store the hash in the database. The FE created hash and BE created hash has to be the same (as per now, it still different)



The feature description are also already written on this thread and on the PR

**Things To Do**
While the majority of the feature parts are already completed, several things to do are still present.

- Create modal for submission reconfirmation dialogue
- Ensure Hash created in FE are the same with hash created in BE for the same submission
- Hashing for File Submission. There could be some work needed with making the file can be hashed with the md5 algorithm.

Overall testing are also need to be done, especially after the points above are completed.

**Note**
The source code contains extensive comments in the related parts of code, developer could refer to that comment if they are confused about what the code are meant to do. To summarize, most of FE code are on exercise/static/chapter.js while backend code are in submission_models.py, exercise/cache/points.py and lib/helpers.py.  As we can see, the bulk of the logical operations are mainly on front end side while the backend side only handles the creation of hash for the storage purposes.

**Comment by Mankro** [comment]
Comments about modal dialogs in chapter.js:

* the html code for the modal has been included in all pages in the base html template: https://github.com/apluslms/a-plus/blob/96a13501050f5f6d12ef9daa6bdacbb0e78eb9f0/templates/base.html#L246

*    chapter.js finds the modal html structure in the initialization: https://github.com/apluslms/a-plus/blob/96a13501050f5f6d12ef9daa6bdacbb0e78eb9f0/exercise/static/exercise/chapter.js#L44

* the jQuery method `aplusModal()` is our extension defined here: https://github.com/apluslms/a-plus/blob/96a13501050f5f6d12ef9daa6bdacbb0e78eb9f0/assets/js/aplus.js#L362-L452

* the function `modal()` is part of the Bootstrap API for opening modal dialogs from JS code: https://github.com/apluslms/a-plus/blob/96a13501050f5f6d12ef9daa6bdacbb0e78eb9f0/assets/js/aplus.js#L417

*    https://getbootstrap.com/docs/3.4/javascript/#via-javascript
