### ISSUE TITLE
Direct navigation to subchapters in the sidebar

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#1016]
Kun kurssimateriaali selaa, toiseen alalukuun siirtyminen on melko hankalaa. Edelliseen ja seuraavaan pääsee sivun ylä- ja alalaidan linkkien kautta, mutta muihin alalukuihin siirtyminen vaatii useamman sivun kautta navigoimisen. Esimerkiksi luvusta 2.2 lukuun 2.4 siirtymiseksi täytyy ensin avata luku 2 ja sitä kautta siirtyä lukuun 2.4.

Kurssimateriaalin sivupalkissa olisi hyvä olla aina näkyvä sisällysluettelo, jota kautta eri alalukujen välillä navigointi olisi sujuvaa. Tällä hetkellä sivupalkki on useissa kursseissa melko tyhjänä. Navigointinäkymä sivupalkissa auttaisi myös kurssimateriaalin kokonaiskuvan hahmottamisessa sitä selatessa. Esimerkiksi Chrome-selaimen PDF-selaimessa on yksinkertainen mutta kätevä navigointinäkymä.

**Comment by Mankro** [comment]
There are two different navigation menus that we are still missing:
1. course structure (table of contents) directly in a sidebar so that one can move from chapter to any other chapter without opening the separate "table of contents" page first.
2. Table of contents inside a chapter so that it is easy to get an overview of the chapter contents (headings). (Like the Affix.js plugin in Bootstrap 3: https://getbootstrap.com/docs/3.4/javascript/#affix)

These are included in the older issue #440. 

Closing this issue as duplicate.
