### ISSUE TITLE
A+ as LTI Tool v1.3: properly set up CSRF tokens and do not exempt unnecessarily

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#1099]
The pull request https://github.com/apluslms/a-plus/pull/1104 added the LTI Tool v1.3 feature. In that PR, the CSRF checks are skipped with exemptions. Investigate if it is possible to enable real CSRF checks in the LTI Tool views.

**Comment by Mankro** [comment]
The pull request #1104 added the LTI Tool v1.3 feature. In that PR, the CSRF checks are skipped with exemptions. Investigate if it is possible to enable real CSRF checks in the LTI Tool views.

**Comment by EerikSaksi** [comment]
Could this be a possible solution? CSRF exempted `LtILaunchView` but validated HTTP requested origin

```
class LtiLaunchView(BaseRedirectView):

    access_mode = ACCESS.ANONYMOUS

    @xframe_options_exempt
    def post(self, request, *args, **kwargs):
        if request.META['HTTP_ORIGIN'] != "http://moodle:8050":
            raise LtiException("Disallowed origin")
```
The valid origins could be defined in a settings variable

```
if hasattr(settings, 'ALLOWED_LTI_ORIGINS') and request.META['HTTP_ORIGIN'] not in settings.ALLOWED_LTI_ORIGINS:
    raise LtiException("Disallowed origin")
```

**Comment by Mankro** [comment]
@EerikSaksi 
> CSRF exempted LtILaunchView but validated HTTP requested origin

Did you mix up CSRF and XFrame since the code only includes `@xframe_options_exempt`?

Checking the request origin is possible, but I am not sure if it is really useful. HTTP clients may set the HTTP request headers freely, thus malicious clients would set the request Origin header to the value we are known to accept in the A+ server.

The LTI launch checks the LTI credentials from the request, right? Don't the credentials already include tokens that only valid LTI clients (e.g., our Moodle server) should know? Would the new LTI Origin check add anything new on top of the existing LTI authentication?

**Comment by Mankro** [comment]
Note the important discoveries listed in the pull request comment:
https://github.com/apluslms/a-plus/pull/1160#pullrequestreview-1386140613
