### ISSUE TITLE
Display personal deadline extensions on a student’s points page

### ISSUE THREAD

**Issue by jsorva** [apluslms/a-plus#1119]
A student’s points page in A+ just shows the official deadlines for each module. Personalized deadlines are not shown. This has repeatedly caused confusion when a student believes there’s something wrong with their personalized deadline. It would be better if the student was able to see the actual deadlines on their points page (and possibly elsewhere?). 

This would also eliminate some confusion in communications between members of course staff, as staff members would also easily see the student’s DL extensions. 

I’m not sure off the top of my head how best to display this on the page.

**Comment by lainets** [comment]
For some reason I thought that you could apply deviations at the module level when in actuality it adds a deviation for each exercise and that this issue was talking about such deviations. My bad.

Yes, a short text about having deviations would be good, and I'd also want some kind of alert indicator next to the closing time of the module for clarity. We could either have the deviations as a tooltip on that indicator or have similar indicator next to each exercise name with the deviation in the tooltip. I don't think there is a good way to fully write out the deviation in the list due to space constraints.
