### ISSUE TITLE
Exercise API field html_url behaves inconsistently

### ISSUE THREAD

**Issue by etanttila** [apluslms/a-plus#1217]
If an exercise has a parent (i.e., is embedded in a chapter or an exercise), the html_url in the API differ between what the ExerciseBriefSerializer and ExerciseSerializer produce.

The brief serializer provides the wanted format of the url (link to the parent with anchor to exercise):
![image](https://github.com/apluslms/a-plus/assets/50318434/0d1cefb7-584d-4163-878c-f874a4b7e8d9)

However, the exercise detail page includes the previous format (to the exercise page): 
![image](https://github.com/apluslms/a-plus/assets/50318434/809a5cf2-0ba6-4f36-be2c-2c459bb787ac)

This is illogical, inconsistent, and causes problems for MOOC-Jutut.

**Comment by etanttila** [comment]
The new behaviour for the brief serializer stems from [commit 'Use the content cache in the course exercise list API endpoint '](https://github.com/apluslms/a-plus/commit/ebf3bc012f61f219893d1e00a86acb00f08aa84e), I'm not directly able to pinpoint why the html_url doesn't work as wanted on the exercise details page.

**Comment by Mankro** [comment]
We looked into this together.

https://github.com/apluslms/a-plus/blob/041919f6d26314d0825b421887ca249bc0d5e0b0/exercise/api/views.py#L81
https://github.com/apluslms/a-plus/blob/041919f6d26314d0825b421887ca249bc0d5e0b0/exercise/api/full_serializers.py#L34
https://github.com/apluslms/a-plus/blob/041919f6d26314d0825b421887ca249bc0d5e0b0/exercise/api/serializers.py#L18
https://github.com/apluslms/a-plus/blob/041919f6d26314d0825b421887ca249bc0d5e0b0/lib/api/serializers.py#L160
https://github.com/apluslms/a-plus/blob/041919f6d26314d0825b421887ca249bc0d5e0b0/lib/api/serializers.py#L66

https://github.com/apluslms/a-plus/blob/041919f6d26314d0825b421887ca249bc0d5e0b0/exercise/exercise_models.py#L304
https://github.com/apluslms/a-plus/blob/041919f6d26314d0825b421887ca249bc0d5e0b0/lib/models.py#L8-L22

`HtmlViewField` can be changed to call `get_display_url()` instead of `get_absolute_url()`.
https://github.com/apluslms/a-plus/blob/041919f6d26314d0825b421887ca249bc0d5e0b0/lib/api/serializers.py#L63-L66
