### ISSUE TITLE
Make hidden courses accessible through LTI

### ISSUE THREAD

**Issue by PasiSa** [apluslms/a-plus#1240]
Sometimes, when A+ content is intended to be accessed only through external LTI 1.3 platform, it is not desirable to let students access it through A+ front page, nor enroll to it from A+, for example to avoid confusion in transferring points to LTI platform. The most straightforward way to do this is to hide the course in A+ settings, but override the hidden property when content is accessed through LTI.

**Comment by Mankro** [comment]
#1290 fixes this issue in the v1.20_stable branch, but the fix needs to be ported to the master branch too.

**Comment by Mankro** [comment]
We talked in the weekly that it is risky to create these cases where students can access courses that are set `visible_to_students = False`, that is, hidden from students. If there are bugs somewhere, the system would leak hidden courses to students, which we absolutely must avoid. Therefore, this issue can be closed and @PasiSa is going to create a new issue for the same need, but with a different approach. We could keep this approach implemented in this issue in the `v1.20_stable` branch, but for the `master` branch, we can implement a new approach that does not reveal hidden courses to students (that is the new issue which hasn't been written yet).

In the master branch, we can use database migrations if need be. There could be a new field in the model `CourseInstance`. It could define if the course may be published via the LTI Tool or not. If we assume that LTI courses should never be accessed directly in A+, then the setting would also hide the course from the A+ front page (and the course archive as well as the instance list of the course code). (It would also disallow access to the course without LTI in the permissions.) The `visible_to_students` field would only be used to really hide the course from students so that there is no way they could enter the course.

**Comment by PasiSa** [comment]
For the master branch we will apply a different approach. See issue #1296 .
