### ISSUE TITLE
Chapters the user has no access to are included in the next/previous links

### ISSUE THREAD

**Issue by lainets** [apluslms/a-plus#1249]
Chapter pages contain links to the next and previous chapter at the top of the chapter content. If the previous or next chapter is a chapter the user doesn't have access to (e.g. a module model solution chapter whose module hasn't been passed), the link to that is shown but clicking on it will cause a 403 page (or a login screen if not logged in) to be shown. This page also does not contain any links back to the course pages or where you came from. 

How to fix this isn't clear, and any implementation probably wont be easy. 

This was mentioned by @jsorva in #1247. Some solutions to this issue may fix that issue as well.

**Comment by PasiSa** [comment]
There was a related bug #1266 with opposite problem: In module view the content chapters were incorrectly hidden due to recent reveal rule changes for model solution chapters (which affects all courses). It seems that the _siblings.html template was forgotten to be updated in the similar way as the _children.html was. Issues #1242 and #1243 are also very much related.
