### ISSUE TITLE
Clarify relationship to http://www.apluslms.com/

### ISSUE THREAD

**Issue by FeldrinH** [apluslms/a-plus#1251]
There is a website http://www.apluslms.com/ that seems to sell an LMS that is also called "A+ LMS". Is that somehow related to this project or is the identical name a coincidence? If it is then it might be worthwhile to add a disclaimer about this somewhere. Also I don't know if there is a potential trademark issue with two distinct learning management systems using the same name.

**Comment by Mankro** [comment]
Our project doesn't have any connection to http://www.apluslms.com/. We work under [Aalto University](https://www.aalto.fi/en) and we don't run any commercial services for e-learning tools. Similar or identical names haven't been selected on purpose, though when a learning platform uses a school grade as the name, it is not going to be very unique or original.

The http://www.apluslms.com/ site feels suspicious with the lack of HTTPS even on the signup form.

Our use of the A+ LMS name has been public at least since the 2013 conference paper:
http://dx.doi.org/10.1109/ICALT.2013.105

**Comment by FeldrinH** [comment]
I guess there isn't much that can be done, though it is kind of unfortunate since it makes finding relevant info online harder.
