### ISSUE TITLE
Remove animation from new notifications badge

### ISSUE THREAD

**Issue by ihalaij1** [apluslms/a-plus#1262]
The big red bouncing animation when students have new notifications has been distracting to some students. The animation is not really needed and should be removed.

**Comment by jsorva** [comment]
Really? I’d much prefer the animation to be on by default — if I’m notifying students about something, it’s generally important to ensure that they see it. Maybe an option for the user to disable the animation instead?

**Comment by oseppala** [comment]
I second making this configurable and having the default to be "animated". It is crucial that the students see a strong visual cue. We spend time to give people feedback and it is easily missed if the notifications are toned down.

It is also unclear what the original request by the students was. Is it truly an issue or merely an opinion on interface design.

**Comment by Mankro** [comment]
This issue was very well defined with a narrow scope: remove the animation. It was also finished according to the request (that is, the animation was removed). I would rather have a new issue for changing/adding the animation. Now you have opened a finished issue and you are requesting the opposite of this issue: add, not remove. This "remove animation" issue should remain closed as completed and a new "add animation" issue could specify a different request.

**Comment by oseppala** [comment]
Ok, As the code has already been shipped and is now in production it likely is a good idea to create a bug report.

 I'll file a bug report suggesting reversal of commit f6afe4e and adding a parameter as #1288
