### ISSUE TITLE
configure_content does not log database errors

### ISSUE THREAD

**Issue by jykesaviaGNH** [apluslms/a-plus#399]
Most error cases (python exceptions) are caught and returned from the edit_course/operations/configure.py configure_content() routine, but if django object.save() throws database exception it will go through and only be displayed in the webview (not logged through logging system).

**Comment by Mankro** [comment]
Actually, no errors in the `edit_course/operations/configure.py configure_content()` function are logged in any server log. The errors are only displayed to the user in the web UI, which should actually be adequate since the user is importing JSON from another system and it is not an error in A+ itself. Furthermore, the errors in django object `save()` are also displayed to the user in the web UI like other errors. Therefore, I don't really see any issue in the error handling.

**Comment by Mankro** [comment]
Closing because I don't see any issue here.
