### ISSUE TITLE
Different submission count between course "exercise results" page and assignment submission view

### ISSUE THREAD

**Issue by mtthwhggns** [apluslms/a-plus#407]
I spotted this in Aalto's production A+ (I'm a student enrolled on O1).

When I view the "exercise results" page, for one assignment I see the following (note the "0/10" submissions):

![Screenshot 2019-11-30 at 19 29 42](https://user-images.githubusercontent.com/6674046/69904228-cba34900-13ac-11ea-8b03-1c05dddb85e4.png)

When I follow the link to the chapter, and the view the assignment, it states I've used one submission (which is currently ungraded).
 
![Screenshot 2019-11-30 at 19 29 55](https://user-images.githubusercontent.com/6674046/69904238-e7a6ea80-13ac-11ea-8e30-17e91ea93eff.png)

It seems to only count graded submissions (this particular assignment is human marked).

This may be the intended behaviour, but it felt wrong that they were not consistent and it caused me a brief moment of intense "did I forget to submit the big assignment before the deadline" panic.

**Comment by Mankro** [comment]
This commit is related to this issue:
https://github.com/apluslms/a-plus/commit/0a9fd39a92bad5cb4fd92fba4b6506b5e6f67d5f
Due to that change, only submissions in the ready status are counted. Submissions to Rubyric exercises tend to remain a long time in the waiting status since they are manually graded.

@alalav1 can start working on this.
