### ISSUE TITLE
LTI: enable branding for instance name

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#423]
Enable branding name for  `tool_consumer_instance_name`.

**Comment by Mankro** [comment]
In the source code, LTI parameters are set here: https://github.com/apluslms/a-plus/blob/master/external_services/lti.py

LTI 1.1 specification that describes tool_consumer_instance_name etc.
https://www.imsglobal.org/specs/ltiv1p1/implementation-guide

**Comment by HenrikSundell** [comment]
@Mankro Thanks for the links! It's still not very clear for me what "enable branding name" means, is this explained somewhere?

**Comment by Mankro** [comment]
@HenrikSundell in the LTI specification, they use the school name as an example. So, the LTI Tool Provider could display the school name in the tool if it receives this parameter (tool_consumer_instance_name) or something similar that counts as the brand of the site.

A+ does not support branding inside A+ either, so we should decide how to do it for LTI. Branding in A+ would allow site maintainers to easily modify the logo and name of the site visible in the web pages. A+ is used in Tampere and Aalto, and currently Tampere has modified some CSS code manually in order to brand the Tampere Plussa site differently from the Aalto plus.cs site.

So, how should we enable branding for LTI? One alternative is to have a setting for the brand name in a-plus/settings.py. That value could be used in the LTI parameter (tool_consumer_instance_name) and at some point, it could be used inside A+ too in order to support branding. @raphendyr comments?

**Comment by raphendyr** [comment]
There is a setting `BRAND_NAME`, which should be used here. If I remember right.that is also used to render the text on top left of the web page.

Another variable interesting variable would be `tool_consumer_instance_description`, but I don't think we have content for that yet. Maybe `WELCOME_TEXT` could be used for that.

**Comment by raphendyr** [comment]
How I see it, is that we should provide fields

* tool_consumer_instance_name=SchoolU
* tool_consumer_instance_description=University of School (LMSng)
* tool_consumer_instance_url=http://lmsng.school.edu

Then the tool provider (e.g. koodisäilö), could tell

```
Login is required, please click the button to be forwarded to SchoolU.

<button>Login via SchoolU</button>

University of School (LMSng)
http://lmsng.school.edu
```

**Comment by HenrikSundell** [comment]
@raphendyr should tool_consumer_instance_url just be the base url or something else?

**Comment by raphendyr** [comment]
> @raphendyr should tool_consumer_instance_url just be the base url or something else?

`BASE_URL` should be good for that. that contains data that is less important (e.g. protocol), but the port number (implied by the protocol) is beneficial. Basically, everu A+ instances should have unique string even if two instances are installed on the same domain (e.g. `foo.com/aplus1` and `foo.com/aplus2` or `foo.com:8080`. To achieve that, I think the BASE_URL is good.
