### ISSUE TITLE
News and information order on the course front page: redesign the UX

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#427]
disable (completely or as an option) the accordion and folding in the news  section of courses' front pages

**Comment by Mankro** [comment]
Juha (O1 course) should clarify this idea and its purpose.

**Comment by jsorva** [comment]
> Juha (O1 course) should clarify this idea and its purpose.

The course front page now has an accordion component that displays course news. Only a very small number of news items are visible by default. I'd prefer all news items to be visible, not just a handful of most recent ones, because sometimes there are things further down on the list that students should notice.

I agree that this is a very low-priority issue. 

P.S. Disabling the folding on A+'s results page (which now hides past content the instant that a deadline is passed) would be slightly higher on my wish list. I don't know if there's a separate issue for that here. 

(In general, I'm not a fan of accordions/folding for course info. They tend to just require extra clicks and increase the risk of confusion/missed information. The benefits seem minimal or nonexistent to me.)

**Comment by annirytkonen** [comment]
maybe we should just mark this as not needed, and close the issue? If this is not needed?

**Comment by Mankro** [comment]
This could be an easy task for the interns, so let's not close this issue.

**Comment by raphendyr** [comment]
> P.S. Disabling the folding on A+'s results page (which now hides past content the instant that a deadline is passed) would be slightly higher on my wish list. I don't know if there's a separate issue for that here.

Created an issue for it: #571
