### ISSUE TITLE
Tags: find a way to tag Fitech student automatically

### ISSUE THREAD

**Issue by raphendyr** [apluslms/a-plus#446]
Aalto (and maybe others) require way to track Fitech students. These students should be automatically tagged, so they can be filttered in results page

**Comment by annirytkonen** [comment]
selvitettävä, kulkeeko shibbolethissa jo nyt sellaista attribuuttia, josta tieto selviäisi: 
* https://wiki.eduuni.fi/display/CSCHAKA/funetEduPerson-skeema
* https://wiki.eduuni.fi/display/CSCHAKA/funetEduPersonSchema2dot2
ja jos noista ei selviä, tiketti servicedesk@aalto.fi ja otsikkoon tai viestin alkuun avainsanoina shibboleth-attribuutit ja IAM niin ohjautuu oikealle porukalle vastattavaksi. Jos sopivaa attribuuttia ei suoraan ole, on toivottavasti mahdollista selvittää ITSin IAM-porukan kanssa, että saataisiinko lisäattribuutti tai voiko jotain yliopistokohtaisista attribuuteista käyttää tähän.

**Comment by raphendyr** [comment]
This information is not available from HAKA, at least for now. Todo, discuss with Aalto IT, if the information could/should be exposed via HAKA.

**Comment by PasiSa** [comment]
I'm proposing to close this, if the goal is to eventually reduce to manageable number of open issues. Currently available APIs do not easily provide this information, so there is nothing we can do about this for now (at least with reasonable effort). Future systems (Salesforce, etc.) may have alternative ways of classifying FItech students. Also, continuation of the FItech project is guaranteed only until 2023.

**Comment by annirytkonen** [comment]
I don't remember why this was needed - I think this was one of the issues copied from Trello. The use case should have been documented, as well. Is this needed e.g. for estimating support needs, general statistics, course grading or something else? 

The background is that Aalto students and Fitech students both have aalto accounts, and it's not possible to separate degree students from Fitech students by their email addresses, as can be done with other external students. Currently, teachers ask students about their background and use tags. 

Assessment data can be exported to a CSV file and soon be sent to Salesforce or MC or both. Is it clear (without this issue) for teachers which students' grades to register in sisu and which not?

maybe @oseppala has additional info?

**Comment by jsorva** [comment]
I’m not 100% sure how this issue originated, but I believe this has to do with the fact that FiTech students need to be treated separately when recording who has completed the O1 MOOC (for funding-related reasons), so it is meaningful to have that info. Having that info correct in student tags would also slightly affect teaching during the course (communications between myself/@oseppala and those students).

Currently, FiTech user tags are assigned automatically from the background questionnaire, but that info is neither complete nor completely reliable (I’ve seen FiTech students sometimes answer things like "CS degree student", for example, instead of FiTech).

Consequently, figuring out who is an actual FiTech student currently relies on manual labor. It’s not a disastrous problem, but it is extra work. If the fix is very difficult, I wouldn’t prioritize it very high. 

(Even if FiTech is discontinued, I expect the same issue will continue to exist in other forms; e.g., open university.)

**Comment by annirytkonen** [comment]
thanks for the info! Currently we count the A+ cumulative credits from Sisu data, and afaik Fitech has their own means of following numbers of students who complete courses. So I would not be worried about funding-related needs. But supporting teachers in supporting students would of course be valuable. If we don't get the accurate data from anywhere, as it seems, this is quite impossible to automate properly. Therefore, I need to conclude that we haven't found a way and I'll close this for now. Of course we can return to this whenever there is the data available.

**Comment by jsorva** [comment]
What does the "archive" label mean?
