### ISSUE TITLE
Add individual users: field should be case-insensitive

### ISSUE THREAD

**Issue by annirytkonen** [apluslms/a-plus#451]
- [x] When adding individual users (e.g. course assistants), the search is case-sensitive; it should be case-insensitive. 
- [ ] The field could also be emptied after the user has been added

**Comment by Mankro** [comment]
This PR should solve at least the case-sensitivity: https://github.com/apluslms/a-plus/pull/479

**Comment by Mankro** [comment]
The case-sensitivity has been fixed with the PR #479 and the fixes committed after it. The second bullet point (emptying the search text field after selecting one search result) should be very easy to fix in the JavaScript: https://github.com/apluslms/a-plus/blob/5351362b40bb03693d0f0d16c79926eec92e4962/assets/js/ajax_search_select.js#L138

I added the label "good first issue" since the remaining part is much easier than the first part (that has been completed).

**Comment by Mankro** [comment]
Emptying the search field after selecting a user: fixed in the PR #926 
https://github.com/apluslms/a-plus/pull/926#issuecomment-988861416
