### ISSUE TITLE
There should be a button for giving a student / selected students points for an expired module automatically.

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#482]
> **Migrated from Trello**

---
**Conversation:**
>**Markku Riekkinen:**
What is the purpose of this? Have these students submitted anything in the expired module?
>
>**Juha Sorva:**
Yes, the idea is that if someone has submitted something late and the teacher is willing to allow it after-the-fact, it should be easy to just add all those points instantly.
>
>One acceptable option would be: 1) teacher gives students personal deadline extension (afterwards) and 2) since the student has already submitted the assignments, they automatically receive official points for their work without anybody having to resubmit anything.
>
>(AFAIK, that second step doesn't currently happen, but I could be wrong.)
>
>**Markku Riekkinen:**
Right. So we could add a button to the inspect submission page that adds a personal deadline extension to the submitter (the length of the extension would be computed so that it is enough to cover the selected submission) and automatically sets the points and status again. It should not be required to send the submission to the grader again since the database should already contain the feedback and service points.
>
>Assistants could only do this if they are allowed to grant deadline extensions and grade submissions.
>
>It is worth noting that A+ does not accept submissions after the deadline by default, so there is no submission in the database at all. However, if unofficial submissions are allowed, this use-case is possible.

**Comment by Mankro** [comment]
The old discussion copied to the issue description mentions personal deadline extensions, but on the other hand, it seems unnecessary to create any deadline extensions when the submission already exists in the database. Deadline extensions should only be used when we want the student to submit again after the deadline.

Another idea:
* There is a button in the inspect submission page for accepting late or unofficial submissions as "normal submissions".
* The button is available to teachers and if the exercise allows assistant grading, then also to assistants.
* The submission record in the database contains the original points set by the grading service as well as the service max points. Verify this first so that I remember this correctly. If this is the case, then we should be able to set the points again in A+ without sending the submission again to the service for regrading.
* When the button is pressed, A+ could set the points based on the original service points again without any late penalties. Unofficial submissions would be set to the "ready" status. The service points may use a different maximum, hence they must be scaled again to the A+ max points.
* Ensure that the related points caches are updated or invalidated when the submissions points are changed.

**Comment by Mankro** [comment]
Closing as duplicate: #892
