### ISSUE TITLE
Better visual highlighting (and/or other UX) of the feedback that students receive for  their answers to a questionnaire

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#490]
> **Migrated from Trello**

**Comment by Mankro** [comment]
The title is quite vague.

One of the problems is that questionnaire feedback does not strongly highlight the feedback (hints) for each question inside the questionnaire. Basically, students do not spot the hints when they quickly glimpse through the feedback. The hints should be so distinct that students can not miss them. Note that questions do not always provide any hints/feedback.

We should also ensure that students easily see when they have answered something correctly or incorrectly. I wonder if the current green and red points badges are adequate. Colour blind people might not be satisfied. @mtthwhggns Any quick comment about this?

@jsorva Do you want to clarify this?

**Comment by Mankro** [comment]
Note that the questionnaire feedback HTML is generated by the MOOC-Grader. A+ simply displays the feedback HTML inside the A+ (chapter) page (in a modal dialogue or for questionnaires also embedded in the page in the exercise "box").

**Comment by mtthwhggns** [comment]
> We should also ensure that students easily see when they have answered something correctly or incorrectly. I wonder if the current green and red points badges are adequate. Colour blind people might not be satisfied. @mtthwhggns Any quick comment about this?

Relying on colours for anything is not good (see [WCAG SC 1.4.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html)). Some users override them in their browser, others can't see them at all, ~1 in 12 men can't tell the difference between red and green to some degree. 

As a point of interest, if you're using Chrome, you can open dev tools, go to the 'Rendering' tab and choose from 'Emulate Vision Deficiencies'. You'll see that one of the more common forms of colour vision deficiency would make them look like this: 

![Colourblind points list](https://user-images.githubusercontent.com/6674046/84881529-a9e28880-b096-11ea-91b7-e6e4b7ebefca.png)

Compared to the original: 

![Original points list](https://user-images.githubusercontent.com/6674046/84881581-be268580-b096-11ea-8a19-88aa45644e7d.png)

Although, it's worth noting that colour is also useful. Imagine a student who magnifies everything on the screen due to blurred vision. They could quickly pick out which of these needs more attention: 

![Blurred points list](https://user-images.githubusercontent.com/6674046/84881681-e1e9cb80-b096-11ea-88b5-871edee68428.png)

With the wider issue, two ideas quickly spring to mind:

- Add a list in the style of "you lost 2 points on question 1" at the top of the questionnaire, so it is the first thing the user sees after submitting, with a clear link to the question to see where the hint is.
- Apply a style to a box around the whole question and hint - in some places I think the text changes colour, but this isn't very noticeable in my opinion.

**Comment by saarasat** [comment]
This is how I would approach this issue and make it better. **The mock-up isn't pixel-perfect yet**, but to get the idea. There also might be some corner-cases I haven't yet touched, but I am sure that when trying out the code and starting to change the actual form, those would come up. Note that, this would require also touching the form in mooc-grader.

**Current situation**

![image](https://user-images.githubusercontent.com/43036333/86255998-79373e80-bbc0-11ea-8287-c8557b782f8d.png)


**What I would do**

**1. Format the area of hints:** 

- Slightly grayer background 
- Remove the bullet 
- Maximum width for the form-group-inputs, so that the icons fit and end-result is cleaner. The width of the hint-area would match the width of the text-box. 

**2. Add default-feedback under each question:** 

- Default texts would be placed under each form-group indicating whether the answer was right. These could be eg. “Correct!”, “Not correct” 
- If the teacher has set any hints, the “Not correct”-text would be over-written with the hint for that question.

**3. Add checkmarks and crosses:** 

- Radiobutton: if correct, a green ✅ next to the correct option would be shown. Additionally the label of the correct answer would be bolded. Currently also the badge color changes to green, so that’ll show that it is correct. If wrong, a red ❌ would be shown next to the wrong answer and the option would be bolded. 
- Checkbox: if correct or wrong, the same as radiobutton with the icons and bolding. If every option has a separate hint set to them, the hints would show up like in the image
- Text-area: if correct, the same as radiobutton. If wrong, the text-area borders are bolded and the default-text is shown below to indicate not correct.  

**4. Validation** 

- For text-questions, if some question is missing a reply or the reply is of wrong type (eg. trying to submit a string when only integer is allowed), the border would be dark yellow and a hint underneath would say something along the lines, “Please check the reply exists and is the correct type”. I need to check the possible validation errors to figure out the appropriate all-around –message here.  

**5. Remove the red texts:** 

- Currently all the options of a wrong choice-type question turn red, if the question is replied wrong. This highlighting would be removed and all text stays at all time the default color. 


**Fixes to the single- and multiple choices**

![image](https://user-images.githubusercontent.com/43036333/86258188-34f96d80-bbc3-11ea-9dd9-3e1ba0271b3f.png)

**Fixes to the text-questions**

![image](https://user-images.githubusercontent.com/43036333/86261496-4e041d80-bbc7-11ea-872e-9c987dce91e8.png)


**After these changes have been done, I would remove the then in a separate pr the redundant feedback-alert-box from the upper-part and emphasize the amount of submissions that the user has left in another manner**

![image](https://user-images.githubusercontent.com/43036333/86262781-fff01980-bbc8-11ea-8a20-44f70e29003d.png)

**Comment by Mankro** [comment]
That looks nice! I have some comments.

1. Sounds good. As a side note, we have this old PR https://github.com/apluslms/a-plus-rst-tools/pull/90 about enumerating the hints so that it would be easier to connect them to the right radio button/checkbox, but that PR could be trashed in favor of these new ideas.
2. Is this about adding feedback under one question or each checkbox in a question? I assume "one question", but I wasn't sure what is covered by a "form-group". Is it really necessary to show the text "Correct" if the green points badge and the green check marks already show correctness? Colour blindness is an issue, though. Screen readers can read hidden `.sr-only` labels. I just wonder if it repeats the same info too much, but perhaps it will work well if the layout is good. Your screenshots look promising.
3. This is otherwise great, but in checkbox questions, one part of the difficulty is based on not knowing which checkboxes are correct when the whole question is simply marked as incorrect. You would reveal valuable information to the student that makes the question easier if they could see which checkboxes are already correct after the first attempt even though they did not answer everything correctly. This is an important part of the challenge that there are multiple combinations of checkboxes and the student does not get hints that make trial-and-error guessing much easier. There is an option that enables partial points in checkbox questions and then students get some points from the question if they answer at least half of the checkboxes correctly.
In addition, when you show the hints under the checkbox group, note that the checkbox text may be much longer than in your screenshot and then it is not as convenient as a label for separating the hints. This has been a problem before that the students can't see which hint is connected to which checkbox.
4. Good.
5. Good.

**Comment by saarasat** [comment]
Good points @Mankro , thanks for these! 

Regarding the 2., I'll try to check with different combinations and questionnaire lengths, to see whether it becomes too much to have the "Correct"-text there on every question or whether the check-mark would be enough. I'll then report different cases in the PR. 

And number 3. And that was actually my initial thought, that the students should not be helped anymore, but then I noticed that the multiple-choice gives hints such as this if there is something right and something wrong:

![image](https://user-images.githubusercontent.com/43036333/86322225-44200000-bc43-11ea-957b-d15f058635fb.png)

So there is one "Correct!" and then another hint that is related to the wrong answer. I thought that these were just hints, not well-connected to the related choices. 

I am trying to think of a way that we could link the hints to the related choices without it becoming obvious that they are right or wrong. Since let's say there is a situation that the user submits one correct choice, and additionally two wrong choices. 
If the wording of the correct solution in anyone says that "yes, because..." or the wording of the wrong solutions have anything like "think.. " or "but..." or "no..." or "almost..." or "rather close...", the moment we link those hints, it would become obvious which is wrong and which is right. Or alternatively if we trigger the hints only when the option chosen is wrong, then the student would know that the one showing no hints is correct. 

In the below example for instance two hints are for the wrong answers and obviously the middle one is for the correct answer. 

![image](https://user-images.githubusercontent.com/43036333/86324245-f3120b00-bc46-11ea-9ad9-34002446b9a3.png)

I think I could talk this through with eg. @jaguarfi to find out what kind of hints teachers normally give to students and finding a good solution for this. Good that you brought this up now!

**Comment by raphendyr** [comment]
Two related notes about implementation.

First, as the html is rendered in mooc-grader, but css is added in A+, thus it's a bit challenge where the css should be stored. Hence, it could be a good place to start trying out kind of a plugin system. First thing to choose is if the css should base on bootstrap or should everything be custom (e.g. if only very few parts use bootstrap and most are replaced with custom). Nevertheless, some parts could be added to A+ assessment tool protocol (i.e. what is available for them to use). E.g. points badges could be named `aplus1-points-badge` and `aplus1-points-badge-success`. Questionnaire stuff could version prefix `.exercise.quiz1  element` or `.exercise  .quiz1  element` (first require changes to A+, second can be done in mooc-grader). In conclusion, the css definitions should be namespaced with versioned classes.

Second, all of the elements that should be stripped a way when the user makes changes, should be marked with a class. This way, we may implement javascript which removes grading related parts when the user changes the form (e.g. remove points badge, when the user edits the question).

**Comment by Mankro** [comment]
About the hints: the teacher decides if the hint reveals the correctness of the checkbox or not. They write the text themselves and it does not have to include works like "correct". The examples in the aplus-manual are quite bad. The hints are tied to certain checkboxes and the UI is supposed to connect the hint to the checkbox, but the UI has been bad. At any rate, the teacher defines the hints for specific checkboxes and I think the intention has always been that the student would know which checkbox is related to the hint. Note that there doesn't have to be any hints at all.

**Comment by jaguarfi** [comment]
Remember to take a look at https://github.com/apluslms/a-plus-rst-tools/pull/90. Basically, your approach is more appealing
