### ISSUE TITLE
A+ shouldn't say "katso palaute/go to feedback" in the popup after a questionnaire's been submitted unless there's actually some written feedback to see

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#493]
> **Migrated from Trello**

Related issues: https://github.com/apluslms/a-plus/issues/492, https://github.com/apluslms/a-plus/issues/490

**Comment by Mankro** [comment]
I guess the problem here is that it is confusing to see an almost empty modal dialogue after submitting a questionnaire. It is also confusing to see the phrase "go to feedback" in the dialogue if there is no feedback to see besides the points.

Is it a good idea to completely remove the modal dialogue for questionnaires? 

A+ does not understand the content inside the feedback HTML. It is only a chunk of HTML from A+'s perspective, thus A+ can not easily know whether the feedback contains any useful comments besides the points. In questionnaires, the feedback HTML contains the whole form with the questions, so it is not feasible to parse "the real feedback" from it. A+ does not know if any "real feedback" with useful comments is included in the HTML.

In very distant future, we could rewrite how A+ handles and renders feedback and then A+ could understand what kind of content is included there. Until then, it is not feasible to recognize whether the feedback contains any "real feedback".

@jsorva do you want to comment? Would you like to simply remove the almost empty modal dialogue for questionnaires?
