### ISSUE TITLE
Add roles to enrollments

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#602]
Currently, the Course model has a many-to-many field to UserProfile for setting the teachers of the course and the CourseInstance model has a many-to-many field to UserProfile for setting the assistants. 

Separating students from the course staff has been problematic. For example, the course points page mixes assistants with the students: https://github.com/apluslms/a-plus/issues/540

There are two approaches to this problem.

1. We don't change the database schema and try to filter teachers and assistants out from the course points page and probably the participants page too.
2. We change the Enrollment model so that it includes a role of the user: student, assistant or teacher. It would make sense to enroll all users in the course, but separate their roles. Currently, teachers should not enroll so that they are not included in the course points page. Enrollment is also needed for storing the pseudonymized name of the user that may be used with, e.g., LTI connections. The old teacher and assistants fields in the Course and CourseInstance fields would be removed.
This approach enables adding new roles in the future, for example, a role for teaching support personnel that are not part of the course staff, but they need to access the course data without having full admin access to the system.

I wrote this issue in favor of alternative 2, but before we commit to it, we should plan ahead. How much would old code have to be changed for alternative 2? At least some user API endpoints are affected, as well as the course points page and the course participants page. All references to assistants, teachers, and enrollments should be checked.

**Comment by Mankro** [comment]
I am first assigning this to @veeraalt . If there is no time for this in July, then @HenrikSundell could step in.

**Comment by raphendyr** [comment]
Someone should consider if we could include "removed" as a role or should it be a separate boolean. Removing teacher/assistant could drop role first to student. Toggling between student and removed should be easy for the person it self (unless we want to support banning).

**Comment by Mankro** [comment]
@raphendyr you mean that instead of deleting enrollments, the enrollment is just flagged as "deleted"? That seems to be the right way to go when we don't want to immediately delete all of the user data in the course. Moodle also has a "deleted" flag for this purpose instead of immediately deleting the data. This also means that when we check for the existence of the enrollment, it is **crucial to check the deleted flag**.

Based on my gut feeling, I think that using "removed" or "deleted" as the role is strange. It also loses the information about the role before deletion. Adding a separate boolean deleted field is simple, but it is worth exploring the role idea.

When we support the removal of enrollments like this, it is essential to enable teachers to remove/unenrol students from the course (so yes, we want to support banning).

**Comment by raphendyr** [comment]
If it is in the role, then it's simple to filter enrolled students (rol == student), though then we don't know what was the status before deleting. Though, I'm not sure if it is important to know if the user was just a participant or the teacher before removing, because if they add them selfs back, they shouldn't become teacher any case.

However, one needs to be sure that the removed role doesn't become like the exercise "hidden" flag.

**Comment by skulonen** [comment]
Some questions regarding the implementation. More to come later as I think about this further...

- > It would make sense to enroll all users in the course, but separate their roles. [...] The old teacher and assistants fields in the Course and CourseInstance fields would be removed.

  Currently, teachers are defined in the course instead of the course instance. After this change, they would be specific to a course instance. Is this okay?
- When editing the course instance's teachers/assistants in the "edit course" view, it would automatically enroll/unenroll the users with the appropriate role, right?
- And clicking the "enroll" button at the course front page would enroll the user with the "student" role?
- Should we support the possibility that a user has multiple enrollments to a course instance, e.g. one as a student and one as an assistant (or other possible future scenarios)? If not, we should make sure that the user's possible existing enrollment is always *updated* instead of creating a new one, e.g. in the hypothetical scenario that the user has enrolled as a student but is later "promoted" to an assistant.

**Comment by skulonen** [comment]
Regarding models:

> The old teacher and assistants fields in the Course and CourseInstance fields would be removed

Maybe we could instead keep the `assistants` field, but redefine it (and `students`, and `teachers`) like so:
```python
students = models.ManyToManyField(UserProfile, related_name="enrolled", blank=True, through='StudentEnrollment')
assistants = models.ManyToManyField(UserProfile, related_name="enrolled", blank=True, through='AssistantEnrollment')
teachers = models.ManyToManyField(UserProfile, related_name="enrolled", blank=True, through='TeacherEnrollment')
```
`StudentEnrollment` & co would be simple proxy models that derive from `Enrollment`, so they would still be stored in the same DB table, and the proxy model would define the default values for the `role` field. This would reduce the amount of changes needed in the codebase, since existing code could still refer to the `students` and `assistants` fields.

Or does this go against the idea of what we're trying to achieve here? If so, let's scrap this idea and just make a new `enrollments` field, and update all old code that refers to `students` and `assistants` to use the new field instead.

**Comment by Mankro** [comment]
> Currently, teachers are defined in the course instead of the course instance. After this change, they would be specific to a course instance. Is this okay?

Good point, I didn't think about that. Anyway, I think it would be beneficial to control editing teachers for each course instance separately. Now that teachers can also modify the teachers themselves without server admin privileges, this could be very convenient. It is not right that teachers can see all course instances even if they were teaching the course only for one year. More fine-grained access control is good.

> When editing the course instance's teachers/assistants in the "edit course" view, it would automatically enroll/unenroll the users with the appropriate role, right?

Yes.

> And clicking the "enroll" button at the course front page would enroll the user with the "student" role?

Yes.

> Should we support the possibility that a user has multiple enrollments to a course instance, e.g. one as a student and one as an assistant (or other possible future scenarios)? If not, we should make sure that the user's possible existing enrollment is always updated instead of creating a new one, e.g. in the hypothetical scenario that the user has enrolled as a student but is later "promoted" to an assistant.

I think adding multiple enrollments to the same user would add a lot of complexity without major advantages. When we list students and we want to filter course staff out, then how does it work if the course staff may also have student role enrollments? Can you see any benefit in having multiple enrollments? 

Indeed, when there is only one enrollment, then existing students could be promoted to assistants. But that is not hard to deal with, right? Django querysets even have a method `get_or_create` which either gets an existing instance or creates a new instance. I suppose it is still clearer and less error-prone to maintain database integrity with unique constraints (only one enrollment instance per user and course instance). In the past, we had a bug: the unique constraint was missing and students could double enroll in the course by double clicking the enroll button. Double enrollments could crash some API endpoints at that time.

The idea of proxy enrollments (StudentEnrollment, TeacherEnrollment): interesting, but perhaps it would be still easier and simpler to use the previous idea and just modify the code (`students` and `assistants` many-to-many fields everywhere). Is removing those fields that much work after all? The proxy enrollments may be dangerous since it is a more advanced Django feature and it may be easier to break it completely.

**Comment by skulonen** [comment]
> I think adding multiple enrollments to the same user would add a lot of complexity without major advantages. When we list students and we want to filter course staff out, then how does it work if the course staff may also have student role enrollments? Can you see any benefit in having multiple enrollments?

One advantage I can see is the ability for teachers to test the course as a student (check that visibility settings and submission limitations are set correctly, etc). But that can be implemented in other ways in the future. Another possible advantage is if we add more roles in the future that are not supersets of each other. For example, "chapter text updater" and "submission grader" could have different, non-overlapping privileges. But in that case it would probably make more sense to add a new "Role" model with a m2m relationship with enrollments.

I agree, I can foresee multiple enrollments adding a lot of complexity and problems. Let's just apply YAGNI and not support them since there isn't an immediate need for them.

> Is removing those fields that much work after all?

No (although it would be even easier if the codebase used type hints, so we could just "find all references"). The idea wasn't really about reducing work, but instead not cluttering the code with additional filters everywhere that students/assistants/teachers are accessed (logic duplication reduces maintainability). But we could also avoid that by adding new `@property`s to the `CourseInstance` class that retrieve the users with a specific role.

> The proxy enrollments may be dangerous since it is a more advanced Django feature and it may be easier to break it completely.

 I agree. The StackOverflow answer that I got this idea from even suggested that it might be a bit of a hack. Let's just be safe and not do that.

**Comment by raphendyr** [comment]
> But in that case it would probably make more sense to add a new "Role" model with a m2m relationship with enrollments.

From current permissions point of view, I think this might be very suitable approach. Personally, I think the single table benefit is to have easy and fast check "are you in the course" and all more complex permissions (e.g. has edit) could then be the same query with a filter (well, db contains check).

> But we could also avoid that by adding new @propertys to the CourseInstance class that retrieve the users with a specific role.

Check out querysets. Those might be well suited for this and also how things are currently done for similar things. At least if I remember right.

From the performance point of view, all changes where the amount of sql inheritance is removed, is beneficial. The magical infrastructure to implement inheritance, adds multiple queries in place where a single query might be sufficient. From my experience, the DB model does not need to be ideal on paper. It needs to be just complex enough to store the data, but optimisation can be used to grow the performance (i.e., store a bit more empty fields to limit number of queries). Personally, I also like to thing extendability, but you already covered that 👍 

Just my 5 cents from an old dev.

**Comment by skulonen** [comment]
@raphendyr Thanks for the input!

> Check out querysets. Those might be well suited for this and also how things are currently done for similar things. At least if I remember right.

You mean the properties would return querysets, like this?

```
@property
def students(self):
	return self.enrollments.filter(role=...) # filtering code here
```

That sounds good to me. Returning a queryset allows the caller to filter the query further before executing it.

**Comment by Mankro** [comment]
> What should happen when an assistant is removed? Should we set their enrollment status to removed, in which case they will have to re-enroll as a student to view the course again? Or should we demote them to students? We can't know if the user was a student directly before being an assistant, unless we store the previous role somewhere.

Set the enrollment status to removed.

**Comment by raphendyr** [comment]
> You mean the properties would return querysets, like this?

I was thinking doing it in `CourseInstanceManager` (see https://github.com/apluslms/a-plus/blob/master/course/models.py#L342). However, the property _might_ be a better solution.

**Comment by skulonen** [comment]
> However, you need to check that code using course_instance.students, doesn't assume it to be something it's not.

Yup, I have already implemented `students` & co as properties. There were basically two situations where I had to fix existing code that referenced the original fields:
- Filtering. You can't filter by properties since they don't actually exist in the database.
- Adding/removing students/assistants/teachers. `students.add` and `students.clear` only work on `ManyToManyField`s.

Aside from those, it went pretty smoothly. Of course, we still need to check that everything works correctly. I'm currently in the process of updating views & the API to support unenrolling/banning students.
