### ISSUE TITLE
Add max_submissions in the course points API endpoint

### ISSUE THREAD

**Issue by Mankro** [apluslms/a-plus#605]
This API endpoint `/api/v2/courses/COURSEID/points/USERID/` for course points shows the user's points in exercises. It also includes some exercise info that is also provided by the exercise endpoint (`/api/v2/exercises/ID/`). The points API already contains `max_points` and `points_to_pass`, so why not also include `max_submissions` (maximum number of allowed submissions)?

Relevant code:
https://github.com/apluslms/a-plus/blob/d34f94b7c9a8e4d22cd28d08968b36787bb344c4/exercise/api/views.py#L420
https://github.com/apluslms/a-plus/blob/d34f94b7c9a8e4d22cd28d08968b36787bb344c4/exercise/api/custom_serializers.py#L76

**Comment by Mankro** [comment]
@raphendyr are you against adding `max_submissions` to the course points API endpoint since the same data can already be retrieved from the exercise endpoint? The points endpoint already includes other exercise details like `max_points`, so excluding `max_submissions` feels like an oversight.

**Comment by raphendyr** [comment]
I guess it's fine. It would be more clear after creating endpoint with the exercise tree as points should be merged with that to get the full picture. max_points and max_submissions kind of belong to the exercise endpoint, but for the convenience those could be included in the points output too. Though, it should be clear that they should be the same _always_ (between points and exercises).

To my knowledge, points endpoint was created to make it possible to render "you have tso many points from stuff A, B and C", so only the information required were added.

**Comment by HenrikSundell** [comment]
Would it make sense to add the `max_submissions` to `ExercisePointsSerializer`  this would mean that  `/api/v2/exercises/22/submitter_stats/2/` would also contain it. 
I think it would only make sense to also have it there too, since it already contains all the same data `max_points` etc. Thoughts @raphendyr ?

**Comment by raphendyr** [comment]
It might be a good idea. I was thinking that the `max_submission` actually does make sense as a per user value, because we have deviations, thus different users might ave different `max_submissions` (for your knowledge too @etanttila). See #424 for requests related this.

If the max_submissions was not calculated to the cache, then it should be added there first.

**Comment by etanttila** [comment]
Having the (general) max_submissions as a part of the user-points API would certainly be helpful as it's the only thing currently that needs to be fetched from the exercise data (all other stuff can be found from the points). At the same time, @raphendyr has a good point that it could be good to take the deviations into consideration as well there, which would also remove the advantage of being able to check the general max submissions from the points API at the same time as everything else. But having the unique deviation taken into consideration there might help with calculating elsewhere whether the submission is official or not (although there one needs to also check the deadline and possible deadline deviation, so it might not help too much).

**Comment by raphendyr** [comment]
> help with calculating elsewhere whether the submission is official or not (although there one needs to also check the deadline and possible deadline deviation, so it might not help too much).

That shouldn't be done elsewhere as the logic for "official" might change, thus the logic shouldn't be copied. Instead the API should provide enough information to solve different usecases.

**Comment by etanttila** [comment]
> That shouldn't be done elsewhere as the logic for "official" might change, thus the logic shouldn't be copied. Instead the API should provide enough information to solve different usecases.

By "elsewhere" I meant "somewhere other than the course points page that I'm working on, the place where it's determined and calculated whether a submission is official or not". Sorry about the misleading wording. I just meant that it wouldn't directly help me in what I'm currently doing, but might help in some other instances.

**Comment by raphendyr** [comment]
If we assume that every endpoint should be logical and include only data relevant for the scope of that endpoint, then we should have an endpoint which provides course specific information, like generic max submissions and points per exercise and so on, and points endpoint (or similar), which would provide a view of the "user on a course", i.e., progress information.

Furthermore, a list endpoints should only create a single database query. If deviations are added using `Exercise.get_submissions_for_student` to the points endpoint, then there would be a db query per exercise. However, something like that is required for #424. To do that correctly, the information should be added to the cache. That would also allow making deviation checks efficiently in other places too. This requires thath the points cache is updated https://github.com/apluslms/a-plus/blob/master/exercise/cache/points.py#L94.

Additionally, it would be a really good idea to drop the exercise details from the points cache (data, which is not specific to the user). To get the exercise specific data, the exercise cache should be used instead https://github.com/apluslms/a-plus/blob/master/exercise/cache/content.py#L64. This could be done by overlaying the two structures, so that when we look from the top, we see the merge of the data (e.g. using layered structure with [dict proxies](https://docs.python.org/3.8/library/collections.html#collections.ChainMap).

As implementing that requires quite much of work, I would delay it until we can allocate more resources to it. I think the actually beneficial part can be achieved just by moving `max_submissions` from detailed exercise serialiser to the brief one (i.e to the list endpoint). This way, the client software can download the exercise list and it will then know limit information to all exercises with a single request. Of course, this is the course base limit and not the actual value for that particular user. Luckily, the endpoint makes that clear. I'm not fond of having user centric endpoint with exercise data.

To conclude, I think we should just move `max_submissions` and `max_points` from https://github.com/apluslms/a-plus/blob/master/exercise/api/serializers.py#L27 to https://github.com/apluslms/a-plus/blob/master/exercise/api/full_serializers.py#L66 for now.

**Comment by raphendyr** [comment]
Most important fields were moved to the list endpoint in #616, which should help a bit. Per user (deviation based) max_submissions should be added to the points API, when that information is in the cache.
