### ISSUE TITLE
Verify whether enrolling to a course should close automatically, if course has ended

### ISSUE THREAD

**Issue by saarasat** [apluslms/a-plus#636]
At https://github.com/apluslms/a-plus/pull/622, came up that at least technically it is possible to have enrolling for a course open, even though the course has already ended. This behaviour should be checked; if there is a reason for this, or whether the enrolling period should actually be tied to the ending of the course. If latter, then the changes should be done accordingly.

**Comment by Mankro** [comment]
I made fixes to the course time settings in the spring 2018 or 2019 (I don't remember anymore). I think I decided at that time that there was no reason to require the enrollment ending time to be earlier than the course closing time. We actually have courses that "close" at a normal time like the end of the year, but some students are still allowed to make late submissions afterwards or just submit solutions for practice without gaining study credits. Particularly, the Programming 1 (MOOC) course may have some activity going on even after the course has ended and it might even be necessary to allow new users to enroll in the course (even so much later after the course's normal starting time) so that they can submit.

To my understanding, there is still no reason to enforce that the enrollment closing time should end before the course closing time. Thus, we shall leave the possibility open for teachers. This basically means that the course closing time is only a "soft ending time" and it does not force all activity to end in the course. This is intended and necessary on some courses. The enrollment opening and closing times set hard time limits for enrollment, while the course lifesupport and archive times set hard limits to model solution visibility and submissions. Each module also has its own opening and (late) closing times as hard limits for normal submissions (unofficial submissions without points can be made even after the late submission deadline until the course archive time).

If I understand the issue correctly, then we have no issue here and no need to change anything and thus we can close this issue.

**Comment by saarasat** [comment]
> If I understand the issue correctly, then we have no issue here and no need to change anything and thus we can close this issue.

Yes, I think @jaguarfi wanted confirmation that whether there is a reason for why the enrolling can end after the course has ended. And there seems to be a valid reason, so we can close this issue.

**Comment by raphendyr** [comment]
Is the reason documented somewhere so we don't need to ask same question again?

**Comment by Mankro** [comment]
> Is the reason documented somewhere, so we don't need to ask the same question again?

No, I don't think so. But most other course settings are undocumented as well. Would it be simplest to add more descriptive help strings to the Django model fields?

**Comment by jsorva** [comment]
From my (O1) perspective, there are a number of valid use cases for enrolling after the course is (officially) over. For example, the materials are open-access, and some students self-pace and don't care about the official schedule. There are some high school classes using the materials at a teacher defined pace. Sometimes, there are valid reasons (e.g., medical) for giving individual students tailored access to the materials at unusual times of the year.

**Comment by raphendyr** [comment]
> No, I don't think so. But most other course settings are undocumented as well. Would it be simplest to add more descriptive help strings to the Django model fields?

Even if it was commented in the code might be enough. Basically, if the information is there where someone might go look for it, then it's good. Also, locations which restrict these values and locations which would be expected to do so, would benefit from a comment.
