### ISSUE TITLE
Navigation links at the bottom and top of the page do not follow a logical tab navigation

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#704]
The navigation links at the bottom of the page are not arranged sequentially. Therefore, when using the tab key to navigate the course content, the navigation goes to the right link (Next) then the left link(Previous) and finally the centre link(Course Material)
![bottom_navigation](https://user-images.githubusercontent.com/10437475/97882581-74c89100-1d2c-11eb-84c0-6a01f7f50665.gif)

**Comment by Mankro** [comment]
The tab order matches the DOM order. The next link is defined first in the HTML, but the pull-right class keeps it in the right corner of the page. Fixing the tab order may require CSS changes so that the next link is still rendered in the right side etc. I agree the priority is low, though it would be nice to fix.
