### ISSUE TITLE
It’s unclear why every item has role="presentation" in the Course Navigation

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#714]

**Comment by jaguarfi** [comment]
Maybe we can change the role to `none` as presented in the following example https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html

**Comment by jaguarfi** [comment]
Actually, the role `none` and `presentation` have the same meaning 🤔 https://www.w3.org/TR/using-aria/#ariapresentation . So we basically need to add the role `menuitem` to the anchor

**Comment by Mankro** [comment]
I guess the role presentation has been used because it removes the semantic meaning of a list. The role is only used on the `<li>` elements. Navigation menu is not a real list so that's why the presentation role removes the list meaning.

This example uses the nav element with ul list without adding aria-role attributes. Perhaps the presentation role is not needed inside the nav element. However, it looks like we should add `aria-label` or `aria-labelledby` to the nav element since our pages have multiple nav elements (navigation landmarks).
