### ISSUE TITLE
Url without course instance should redirect to the current or last instance

### ISSUE THREAD

**Issue by jaguarfi** [apluslms/a-plus#746]
> It seems that the URL https://plus.cs.aalto.fi/o1 is no longer 
redirecting properly (to the newest O1 instance), presumably because of 
the recent update.
>
>I would greatly appreciate a quick fix, since that URL is frequently 
used by me, public to students, and public also to the international 
computing education community via research papers as a window to 
teaching at Aalto.
>
>It would also be nice to streamline this process somehow so that future 
updates do not similarly break the redirect. (Perhaps simply by 
supporting such generic course-offering-independent URLs in general?)
>
>**Juha Sorva**

**Comment by jaguarfi** [comment]
It seems this is implemented only for the o1 course, but all courses may benefit from this.

**Comment by Mankro** [comment]
> It seems this is implemented only for the o1 course, but all courses may benefit from this.

Yes exactly. The plus.cs.aalto.fi/o1 redirect has been hardcoded in the HTTP server Apache/NGINX settings. It is not an A+ feature, but it would make sense as an A+ feature. In the new feature, the page should list all the instances of that course, though, instead of redirecting to one specific instance.

**Comment by Mankro** [comment]
Closing this issue as duplicate: 
* https://github.com/apluslms/a-plus/issues/522
* https://github.com/apluslms/a-plus/issues/578
