### ISSUE TITLE
Course page is rendered with invalid URLs even when the validation rejects the new URL value

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/a-plus#782]
Under A+ edit course, course tab, when you try to enter the instance key/url "instances", it does not pass form validation, but the links in the page are anyway rendered with the new value "instances". Those links do not work since there is no course instance with that url.

This issue originates from #772.

Edit:
The form has validation and the url value "instances" does not pass the validation. However, when you see the validation error in the form, you can see that the links to the course already use the instance url "instances" even though that value has not been written to the database. If you try to open the "content" tab under the A+ edit course section, you get HTTP 404 Not found. The URL clearly has the course instance url "instances", which is very wrong.

**Comment by jaguarfi** [comment]
I think it is validating the Url field.
![image](https://user-images.githubusercontent.com/10437475/107486730-0d717700-6b8e-11eb-9708-3ce435afe5e8.png)

**Comment by Mankro** [comment]
@jaguarfi Yes, that is what I tried to say. The form has validation and the url value "instances" does not pass the validation. However, when you see the validation error in the form, you can see that the links to the course already use the instance url "instances" even though that value has not been written to the database. If you try to open the "content" tab under the A+ edit course section, you get HTTP 404 Not found. The URL clearly has the course instance url "instances", which is very wrong. This bug probably existed before your new course instance list page, but it wasn't visible since all url values were valid. 

Actually, if the instance url contains spaces, what will happen? Whitespace could break the URL and the course would be basically broken and inaccessible.
