### ISSUE TITLE
Same submission communication error message used despite where the error is

### ISSUE THREAD

**Issue by etanttila** [apluslms/a-plus#852]
The same error message is displayed whether there is a communication error between A+ and Grader or the browser and A+. However, it would be useful for the user to be able to differentiate between these two (for example, when the problem is between the browser and A+, it can result from the user not being connected to the internet).
The key of the error message in question is "SUBMISSION_ERROR_ALERT_COMMUNICATION_ERROR_W_SERVICE"

**Comment by Mankro** [comment]
In addition, in the submit modal dialog in chapters, the error message is displayed inside a progress bar. That is not a good idea since it is hard to read and the latter half of the message disappears since it does not fit into the progress bar.

One internal ticket presents that issue:
https://rt.cs.aalto.fi/Ticket/Display.html?id=20170

**Comment by Mankro** [comment]
> The same error message is displayed whether there is a communication error between A+ and Grader or the browser and A+. However, it would be useful for the user to be able to differentiate between these two (for example, when the problem is between the browser and A+, it can result from the user not being connected to the internet). The key of the error message in question is "SUBMISSION_ERROR_ALERT_COMMUNICATION_ERROR_W_SERVICE"

#1185 closed this issue, but it does not differentiate error messages for (1) when the user's browser can not connect to A+ and (2) when A+ can not connect to the grader.
