### ISSUE TITLE
Improve the buttons in the exercise frame header

### ISSUE THREAD

**Issue by skulonen** [apluslms/a-plus#856]
From August 2021 webinar feedback:

The buttons in the exercise frame header ("show model solutions" etc) often go unnoticed by students. They should be made more noticeable in some way, e.g. by increasing their size.

It was also commented that students don't really read the text in the header. Perhaps it should be some other color that is not used elsewhere in the course materials?

**Comment by EerikSaksi** [comment]
After considering the possible options we have come to the conclusion that changing the colour of the button shouldn't be done because of accessibility. Changing the size looks bad, and looks out of place. I think that the best solution would be to create a bootstrap tooltip over the show model solutions button, which is shown conditionally based on a localstorage value. This would draw the users attention once but wouldn't show it repeatedly (unless the user clears local storage or swaps browsers)
