### ISSUE TITLE
Submitters field cleared on missing input in deadline deviations

### ISSUE THREAD

**Issue by ahrenberg** [apluslms/a-plus#998]
If I forget to enter some required input (e.g. the number of days, or the assignment) for a deadline deviation and mistakenly click 'Save', the field of submitters are cleared. It would be nice if the contents of this field could be kept on reload just as it is for the module/assignment fields. (Or if 'Save' was greyed out until all required input has been entered if submitters can't be held in state.)

**Comment by annirytkonen** [comment]
added to backlog --> to be scheduled

**Comment by Mankro** [comment]
There may be a couple of other forms that may suffer from the same issue in the customized submitters multi-select field. I should check their status and we could then open another issue with a broader scope to fix the groundwork properly.

**Comment by Mankro** [comment]
The submitter field uses the custom form field type `UsersSearchSelectField`.
https://github.com/apluslms/a-plus/blob/d14143904bf04f7016088ae460e81d18ccd3f736/deviations/forms.py#L36-L41

`UsersSearchSelectField` already includes a feature (`initial_queryset`) for defining the initial choices that are loaded upon the page load. We should try to use that also when the form submission is first rejected due to missing inputs and the form is rendered again.

https://github.com/apluslms/a-plus/blob/d14143904bf04f7016088ae460e81d18ccd3f736/lib/fields.py#L90-L98

The form for adding deadline deviations currently always sets `UsersSearchSelectField.initial_queryset` to an empty queryset, which explains why the choices are lost when the form submission is rejected.

https://github.com/apluslms/a-plus/blob/d14143904bf04f7016088ae460e81d18ccd3f736/deviations/forms.py#L36-L53

We need to find the right way to preserve the user's input value when the form submission fails to validation. Perhaps, the `clean()` method of `UsersSearchSelectField` could be overridden to set `initial_queryset` back to the input value. The form constructor before that has set `initial_queryset` to the empty queryset.

---------------------------------------------------------------

> There may be a couple of other forms that may suffer from the same issue in the customized submitters multi-select field. I should check their status and we could then open another issue with a broader scope to fix the groundwork properly.

Any form using `UsersSearchSelectField` might be affected.

**Comment by Mankro** [comment]
The commit https://github.com/apluslms/a-plus/commit/b16e75e300bb36b2323297770375c88e309cba24 fixes the `clean()` in the class `SearchSelectField` and thus, this issue has been fixed in all forms that use `UsersSearchSelectField`.
